# Generated by Django 5.1.4 on 2024-12-23 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_alter_chairperson_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chairperson',
            name='gender',
            field=models.CharField(choices=[('M', 'MALE'), ('F', 'FEMALE')], default='M2', max_length=1),
        ),
    ]
